import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-10 w-full p-5 px-10">
          {/* <nav>
            <ul className="flex flex-row justify-start gap-5">
              <li className="underline">
                <Link href="/">Home</Link>
              </li>
              <li className="underline">
                <Link href="/users">Local users</Link>
              </li>
              <li className="underline">
                <Link href="/starwars">Starwars characters</Link>
              </li>
            </ul>
          </nav> */}
        </header>
        <main className="container px-10">{children}</main>
      </body>
    </html>
  );
}
